# Generated by Django 5.1 on 2024-08-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decodeimage',
            old_name='image',
            new_name='imag',
        ),
        migrations.RenameField(
            model_name='generateimage',
            old_name='image',
            new_name='imag',
        ),
    ]
